### ISSUE TITLE
Where is the files such as './examples/all_refer_questions_train.json'

### ISSUE THREAD

**Issue by Xiaolong-RRL** [UMass-Foundation-Model/3D-LLM#26]
Dear author:

Thanks for your interesting work.

When I run the following command:

`python-m torch.distributed.run --nproc_per_node=8 train.py --cfg-path lavis/projects/blip2/train/3dvqa_ft.yaml`

I found that the three annotations files in 3dvqa_ft.yaml do not exist. How can I obtain them? Or do I need to generate them locally?
```
build_info:
  annotations:
    train:
      storage: ./examples/all_refer_questions_train.json
    test:
      storage: ./examples/all_refer_questions_val.json
    val:
      storage: ./examples/all_refer_questions_val.json
```

Thanks!!
